/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class VentanaRegistroPaciente extends javax.swing.JFrame {
    private ImageIcon imagen;
    private Icon icono;
    /**
     * Creates new form VentanaRegistroPaciente
     */
    public VentanaRegistroPaciente() {
        super("Registro Paciente");
        
        initComponents();
        setLocationRelativeTo(null);
        this.setImagenes(jbntSignosVitales, "src/Imagenes/signosvitales.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jLNombres = new javax.swing.JLabel();
        jTFNombresPaciente = new javax.swing.JTextField();
        jLApellidos = new javax.swing.JLabel();
        jTFApellidosPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFCedulaPaciente = new javax.swing.JTextField();
        jLFechaNacimiento = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFemailPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFTelefonoPaciente = new javax.swing.JTextField();
        jbntSignosVitales = new javax.swing.JButton();
        jLSignosVitales = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbntCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTitle.setText("REGISTRO PACIENTE");
        jPanel2.add(jlbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 11, -1, -1));

        jLNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNombres.setText("Nombres:");
        jPanel2.add(jLNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 89, -1, -1));
        jPanel2.add(jTFNombresPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 85, 170, 29));

        jLApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLApellidos.setText("Apellidos:");
        jPanel2.add(jLApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 136, -1, -1));
        jPanel2.add(jTFApellidosPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 124, 170, 29));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cedula:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 223, -1, -1));
        jPanel2.add(jTFCedulaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 219, 170, 28));

        jLFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLFechaNacimiento.setText("Fecha de Nacimiento:");
        jPanel2.add(jLFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 184, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("E- mail: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 269, -1, -1));
        jPanel2.add(jTFemailPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 265, 170, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Teléfono:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 316, -1, -1));
        jPanel2.add(jTFTelefonoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 312, 170, 28));
        jPanel2.add(jbntSignosVitales, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 84, 85, 77));

        jLSignosVitales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLSignosVitales.setText("Añadir Signos Vitales");
        jPanel2.add(jLSignosVitales, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 179, -1, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 399, 99, 31));

        jbntCancelar.setText("Cancelar");
        jPanel2.add(jbntCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 399, 86, 31));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if (jTFNombresPaciente.getText().isEmpty() || jTFApellidosPaciente.getText().isEmpty() || jTFCedulaPaciente.getText().isEmpty() ||  jTFTelefonoPaciente.getText().isEmpty() || jTFemailPaciente.getText().isEmpty()) {
            JOptionPane.showInternalMessageDialog(null, "Rellenar los campos vacíos");
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroPaciente().setVisible(true);
            }
        });
    }
    
        private void setImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT
                )
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
        private void setImagenes(JButton jB, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        jB.getWidth(),
                        jB.getHeight(),
                        Image.SCALE_DEFAULT
                )
        );
        jB.setIcon(this.icono);
        this.repaint();
        
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLApellidos;
    private javax.swing.JLabel jLFechaNacimiento;
    private javax.swing.JLabel jLNombres;
    private javax.swing.JLabel jLSignosVitales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFApellidosPaciente;
    private javax.swing.JTextField jTFCedulaPaciente;
    private javax.swing.JTextField jTFNombresPaciente;
    private javax.swing.JTextField jTFTelefonoPaciente;
    private javax.swing.JTextField jTFemailPaciente;
    private javax.swing.JButton jbntCancelar;
    private javax.swing.JButton jbntSignosVitales;
    private javax.swing.JLabel jlbTitle;
    // End of variables declaration//GEN-END:variables
}
